
name: "Dev Terraform Ifras Workflow"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main  
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-planning-job:
    name: terraform-planning-job 
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ae2efbf9-a607-4fa8-987a-9811135891d8
          tenant-id: 387597f4-2c73-443d-93f5-fe6be49ec6c7
          subscription-id: c4392c89-177c-49fd-abc6-1b1d293e65b7
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environments/Dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Environments/Dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Environments/Dev
  terraform-apply:
    runs-on: self-hosted
    needs: terraform-planning-job
    # if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ae2efbf9-a607-4fa8-987a-9811135891d8
          tenant-id: 387597f4-2c73-443d-93f5-fe6be49ec6c7
          subscription-id: c4392c89-177c-49fd-abc6-1b1d293e65b7
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: Environments/Dev  







        
