
name: "Dev Terraform Ifras Workflow"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main  
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-planning-job:
    name: terraform-planning-job 
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e56aba2e-309d-4313-8091-e641c4c5c43b
          tenant-id: 8810bad7-7f76-4bba-8b17-d6d297d7bdd7
          subscription-id: 2a238ca4-a95b-43d2-846c-1618b53c6203
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environments/Dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Environments/Dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Environments/Dev
  terraform-apply:
    runs-on: self-hosted
    needs: terraform-planning-job
    # if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e56aba2e-309d-4313-8091-e641c4c5c43b
          tenant-id: 8810bad7-7f76-4bba-8b17-d6d297d7bdd7
          subscription-id: 2a238ca4-a95b-43d2-846c-1618b53c6203
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Environments/Dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: Environments/Dev  







        
